# Generated by Django 5.2 on 2025-05-22 08:11

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.upload_to),
        ),
        migrations.AddField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.upload_to),
        ),
        migrations.AlterField(
            model_name='messages',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
