# Generated by Django 5.2 on 2025-06-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messages_document_messages_image_alter_messages_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
