# Generated by Django 5.2 on 2025-06-22 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_group_messagetype_remove_chat_participants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userchat',
            name='user',
        ),
        migrations.AddField(
            model_name='userchat',
            name='user',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
