# Generated by Django 5.2 on 2025-06-22 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_userchat_unique_together_remove_userchat_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchat',
            unique_together={('user', 'chat')},
        ),
        migrations.RemoveField(
            model_name='userchat',
            name='user',
        ),
        migrations.AddField(
            model_name='userchat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
