# Generated by Django 5.2 on 2025-06-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='\\media\\chat_media\\15\\avatar.png', null=True, upload_to='\\media\\'),
        ),
    ]
